$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: mnist-endpoint-865021
model:
  path: ../mnist-model-1/model
code_configuration:
  code: ../mnist-model-1/onlinescoring
  scoring_script: score.py
environment:
  $schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
  name: minimal-inference-plus-conda
  image: mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference:latest
  conda_file: ../mnist-model-1/environment/conda.yml
instance_type: Standard_DS3_v2
instance_count: 1
