$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: mnist-endpoint-271934-mlflow
model: azureml:mnist-model-1-mlflow@latest
instance_type: Standard_DS2_v2
instance_count: 1
